# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DEH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DEH
pod 'SwiftyJSON'
pod 'Alamofire', '~> 5.2'
  target 'DEHTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DEHUITests' do
    # Pods for testing
  end


end
